---
title: "Week6_2"
author: "Heather"
date: "3/3/2022"
output: 
  html_document:
    theme: cerulean
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = "../Outputs/", warning = FALSE, message = FALSE)
```

# Intro

Today we are going to work with the penguin data to learn *RMarkdown*.

# Load Libraries
```{r}
library(tidyverse)
library(here)
library(palmerpenguins)
library(palettetown)
library(kableExtra)
```

# Inspect the data
```{r}
glimpse(penguins)
```


# Data analysis
```{r penguin, out.width="80%", fig.asp=0.8, fig.align='center', fig.cap="This is a plot", echo=FALSE}
penguins %>% 
  ggplot(aes(x = flipper_length_mm,
             y = body_mass_g))+
             #color = species))+
  geom_point()+
  geom_smooth(method = "lm")+
  labs(x = "Flipper length (mm)",
       y = "Body mass (g)",
       title = "Body Mass vs Flipper Length")+
  theme_grey()+
  scale_color_manual(values = pokepal(7))
```

```{r}
penguins %>%
  group_by(species) %>%
  summarise(billmean = mean(bill_length_mm, na.rm = TRUE)) %>%
  kbl() %>%  # make it a kable table
  kable_classic()%>%
  row_spec(2, bold = T, color = "white", background = "darkblue") %>% 
  kable_styling(full_width = FALSE)
```

